# Generated by Django 2.0.7 on 2018-07-24 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now=True)),
                ('plays', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('usrname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('passwd', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('ava', models.CharField(blank=True, default='', max_length=200)),
                ('following', models.IntegerField(default=0)),
                ('followers', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='owned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
    ]
