# Generated by Django 2.0.7 on 2018-07-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180725_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detailpl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlistid', models.IntegerField()),
                ('songid', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='detailpl',
            unique_together={('playlistid', 'songid')},
        ),
    ]
