# Generated by Django 2.0.7 on 2018-07-25 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180725_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpl',
            name='playlistid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Playlist'),
        ),
        migrations.AlterField(
            model_name='detailpl',
            name='songid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Song'),
        ),
    ]
