# Generated by Django 2.0.7 on 2018-07-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180725_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='src',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
