# Generated by Django 2.0.7 on 2018-07-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180725_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='src',
            field=models.FileField(upload_to='media/'),
        ),
    ]
