# Generated by Django 2.0.7 on 2018-07-29 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180729_0445'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='follow',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='following',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
