# Generated by Django 2.0.7 on 2018-07-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20180729_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ava',
            field=models.FileField(upload_to='static/imgs/ava'),
        ),
    ]
