# Generated by Django 2.0.7 on 2018-07-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180729_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ava',
            field=models.FileField(upload_to='media/ava'),
        ),
    ]
