# Generated by Django 2.0.7 on 2018-07-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20180729_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ava',
            field=models.FileField(upload_to='media/'),
        ),
    ]
