# Generated by Django 2.0.7 on 2018-07-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_song_ava'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
