# Generated by Django 2.0.7 on 2018-08-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_user_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='ava',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
