# Generated by Django 2.0.7 on 2018-08-02 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_playlist_ava'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='album',
        ),
    ]
