# Generated by Django 2.0.7 on 2018-08-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_playlist_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
