# Generated by Django 2.0.7 on 2018-08-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20180805_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ava',
            field=models.FileField(default='default_avatar.jpg', upload_to='media/'),
        ),
    ]
