# Generated by Django 2.0.7 on 2018-08-05 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
