# Generated by Django 2.0.7 on 2018-08-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_delete_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='src',
            field=models.FileField(default='default_audio.mp3', upload_to='media/'),
        ),
    ]
